# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='myblog.tags', verbose_name='博客标签'),
        ),
    ]
