# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20180301_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='博客标题')),
                ('subtitle', models.CharField(max_length=80, verbose_name='博客副标题')),
                ('keywords', models.CharField(max_length=100, verbose_name='关键字')),
                ('description', models.CharField(max_length=300, verbose_name='描述')),
                ('blogsNum', models.IntegerField(default=0, verbose_name='日志数量')),
                ('categorysNum', models.IntegerField(default=0, verbose_name='分类数量')),
                ('tagsNum', models.IntegerField(default=0, verbose_name='标签数')),
            ],
            options={
                'verbose_name': '博客系统设置',
                'verbose_name_plural': '博客系统设置',
            },
        ),
    ]
