# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='blogsNum',
            new_name='blogNum',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='categorysNum',
            new_name='categoryNum',
        ),
    ]
