# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20180301_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='tagsNum',
            new_name='tagNum',
        ),
    ]
