# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 09:09
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20180301_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(null=True, verbose_name='博客内容'),
        ),
    ]
