# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ips',
            fields=[
                ('ip', models.CharField(default='0.0.0.0', max_length=20, verbose_name='ip地址')),
                ('ip_port', models.IntegerField(default=0, verbose_name='端口')),
                ('ip_hashid', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='ip哈希值')),
            ],
            options={
                'verbose_name': 'ip_api',
                'verbose_name_plural': 'ip_api',
            },
        ),
    ]
